
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[418] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       66,   64,   47,    3,    3,   22,   57,   49,   20,   64,
       16,   26,    7,   24,    8,   19,   64,    9,    1,    1,
       28,   18,    6,   12,   49,   49,   17,   27,   32,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   14,   64,   25,   52,   51,
       51,   55,   54,   54,   55,   62,   59,   59,   58,   60,
       63,   65,    3,   21,   49,    5,   48,   29,    2,    2,
        0,   53,   50,    0,    2,    0,    0,    0,    1,    0,
       30,   15,   10,   11,   31,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   48,   49,
       49,   49,   49,   49,   49,   49,   49,   13,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   23,   51,   54,
       56,   59,   60,   61,    0,    2,    0,    0,    0,    0,
        0,    2,    2,    0,    0,    0,    2,    2,    0,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       48,   49,   49,   49,   38,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,    2,    0,    2,    2,
        2,    0,    0,    0,    2,    0,    0,    0,    2,    2,
        0,    2,    2,    0,    0,    0,    0,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       37,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,    4,   45,   49,   49,    2,    0,    2,
        2,    0,    0,    2,    2,    0,    2,    2,    0,    2,
        2,    0,    0,    2,    2,    2,   49,   49,   49,   49,
       49,   49,   34,   49,   49,   49,   49,   48,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   48,   49,   49,   46,    2,    2,    2,    0,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,   49,   44,   48,   49,   49,   49,   49,   36,
       49,   49,   49,   49,   49,   49,   49,   49,   41,   42,
       43,   49,   49,   49,   49,    2,    2,    2,    2,    2,
        2,   35,    2,    2,    2,    2,    2,    2,    2,   48,
        0,   49,   33,   49,   49,   49,   49,   49,   49,   49,
       49,   49,    2,    2,    2,    0,    0,   49,   49,   49,
       49,   49,   49,    2,    2,    0,    0,   49,   49,   49,

        0,    0,   49,    0,    0,   49,    0,    0,    0,    0,
        0,    0,    0,    0,   40,   39,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,    9,    9,    9,    9,   26,    9,
        9,    9,   27,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   28,    9,    9,    9,    9,    9,    9,    9,
       29,   30,   31,   32,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,    9,   43,   44,   45,   46,
       47,   48,    9,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[424] =
    {   0,
        0,    0,   58,   59,   62,   63,   66,   67,    0,    0,
      747,  748,  748,  748,  743,  721,  748,    0,  748,  733,
      748,  748,  748,  728,  748,   56,   62,   65,   90,   74,
      748,   62,  718,   63,  695,   58,  748,  748,  748,   43,
       68,   85,   42,   81,   96,  693,   96,  692,   99,   97,
      700,  103,   50,  690,  695,  748,  676,  748,  748,  748,
      731,  748,  748,  730,  713,  748,  748,  728,  748,  126,
      748,  748,  748,  748,    0,  748,  748,  748,  140,  143,
      692,  748,  748,  708,  132,  162,  169,  171,  176,  178,
      748,  748,  748,  748,  748,  677,  678,  676,  675,  674,

      676,  684,  670,  117,  686,  685,  672,  678,  664,  665,
      662,  662,  668,  665,  663,  660,  657,    0,  659,  155,
      660,  654,  650,  659,  666,   71,  666,  649,  652,  113,
      650,  655,  650,  159,  151,  168,  653,  748,  748,  748,
      748,  748,  748,  748,  673,  196,  198,  200,  203,  647,
      217,  232,  206,  239,  228,  210,  243,  246,  251,  654,
      649,  639,  638,  650,  643,  652,  647,  646,  647,  633,
      631,  191,  646,  644,  640,  632,  638,  625,  640,  639,
        0,  625,  127,  620,  632,  629,  626,  623,  623,  612,
      613,  619,  610,  612,  609,  617,  620,  606,  620,  605,

      607,  607,  614,  614,  616,  605,  254,  225,  270,  261,
      275,  608,  279,  626,  289,  286,  300,  265,  303,  305,
      625,  308,  310,  314,  319,  324,  328,  605,  598,  605,
      593,  592,  602,  596,  597,  587,  585,  593,  582,  589,
        0,  586,  593,  586,  578,  590,  578,  592,  576,  571,
      589,  588,  583,  578,  570,  567,  575,  580,  566,  578,
      572,  558,  561,    0,    0,  559,  571,  338,  587,  347,
      349,  352,  354,  357,  368,  556,  371,  379,  585,  390,
      382,  387,  393,  398,  401,  404,  567,  564,  558,  568,
      550,  566,    0,  553,  554,  559,  559,  551,  549,  542,

      546,  552,  552,  549,  537,  551,  550,  539,  548,  532,
      541,  532,  530,  537,  536,    0,  407,  409,  412,  536,
      415,  418,  426,  429,  434,  437,  452,  445,  448,  455,
      459,  462,  527,    0,  557,  538,  526,  505,  505,    0,
      504,  497,  514,  514,  515,  509,  502,  482,    0,    0,
        0,  487,  472,  474,  447,  466,  469,  473,  476,  480,
      483,  748,  490,  487,  494,  497,  501,  504,  508,  459,
      424,  410,    0,  405,  370,  358,  357,  348,  336,  335,
      333,  327,  511,  515,  518,  315,  308,  305,  306,  313,
      300,  290,  267,  522,  525,  280,  253,  252,  254,  231,

      234,  255,  230,  212,  199,  188,  155,  138,  152,  108,
       99,   93,   69,   50,  748,  748,  748,  558,  561,  564,
      567,   87,  570
    } ;

static const flex_int16_t yy_def[424] =
    {   0,
      417,    1,  418,  418,  419,  419,  420,  420,  421,  421,
      417,  417,  417,  417,  417,  417,  417,  422,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  422,  422,  417,  417,  417,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  423,
      417,  417,  417,  417,  422,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  422,  422,  422,  422,  422,

      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,

      422,  422,  422,  422,  422,  422,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,

      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  422,
      417,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  417,  417,  417,  417,  417,  422,  422,  422,
      422,  422,  422,  417,  417,  417,  417,  422,  422,  422,

      417,  417,  422,  417,  417,  422,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,    0,  417,  417,  417,
      417,  417,  417
    } ;

static const flex_int16_t yy_nxt[809] =
    {   0,
       12,   13,   14,   13,   15,   13,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   18,   35,   36,   37,   12,
       38,   39,   18,   40,   41,   42,   43,   44,   45,   46,
       18,   47,   18,   48,   18,   49,   18,   50,   51,   52,
       53,   18,   54,   55,   18,   18,   18,   56,   57,   58,
       60,   60,   61,   61,   63,   63,   64,   64,   67,   67,
       68,   68,   77,   69,   69,   65,   65,   99,   82,  108,
       78,   79,   80,   83,   91,   92,   94,   95,  109,   75,
      134,   85,  100,   89,   89,   70,   70,   84,  135,   87,

      416,   71,   71,   71,   71,   81,   90,   85,   97,   86,
       86,   87,  190,   98,  101,   87,  102,  191,  104,  415,
       71,   71,   88,  103,  110,  105,  111,   87,  106,  113,
      125,  107,  122,  144,  118,  112,  123,  114,  414,  115,
      119,  120,  116,  129,  413,  126,  195,  145,  127,  412,
      124,  152,  153,  130,  131,  144,  132,  154,  133,  146,
      146,  196,  146,  146,  144,  147,  168,  169,  147,  154,
      246,  144,  148,  247,  144,  149,  144,  147,  411,   85,
      147,   86,   86,  156,  202,  156,  410,   87,  157,  158,
       86,  159,  409,   85,  155,   89,   89,   89,   89,   87,

      200,   87,  203,  155,  184,  185,  181,  201,   90,  204,
       90,  205,  208,   87,  208,  146,  146,  209,  210,  146,
      211,  147,  146,  146,  181,  215,  215,  156,  149,  157,
      158,  154,  149,  147,   85,  149,  213,  213,  217,  214,
      237,  238,   87,  154,  209,  210,  408,   86,   86,  213,
      221,  215,  215,  218,   87,  218,  208,  154,  219,  220,
      155,  407,  222,  223,  216,  222,  223,  406,   85,  154,
      226,  226,  405,  268,  268,  224,   87,  269,  225,  147,
      270,  271,  404,  227,  219,  220,  268,  403,   87,  270,
      271,  147,  181,  273,  274,  274,   85,  218,  213,  213,

      147,  181,  272,  402,   87,  215,  278,  275,  215,  215,
      279,  213,  147,  401,  154,  221,   87,  181,  217,  215,
      215,  217,  280,  281,  280,  281,  154,  222,  223,  222,
      223,  400,  217,  285,  286,  282,  181,  283,  285,  285,
      224,   85,  225,  226,  226,   85,  225,  226,  226,   87,
      181,  225,  399,   87,  269,  398,  227,  268,  268,  397,
      227,   87,  396,  147,  181,   87,  270,  271,  270,  271,
      268,  318,  319,  318,  318,  147,  274,  274,  393,  272,
      392,  273,  147,  181,  273,  391,  273,  274,  274,  275,
      321,  321,  390,  147,  147,  389,  154,  279,  322,  322,

      275,  280,  281,  321,  154,  147,  325,  326,  154,  280,
      281,  323,  325,  325,  283,  388,  154,  327,  328,  283,
      222,  223,  282,  330,  331,  283,  356,  357,  270,  271,
      329,  359,  360,  225,  321,  321,  332,  322,  322,  358,
      154,  273,  181,  154,  361,  322,  322,  321,  363,  364,
      323,  154,  154,  280,  281,  154,  366,  367,  323,  221,
      181,  365,  221,  154,  330,  331,  283,  327,  328,  368,
      387,  330,  331,  269,  330,  331,  386,  332,  330,  331,
      329,  330,  331,  269,  369,  359,  360,  369,  359,  360,
      382,  332,  356,  357,  332,  359,  360,  279,  383,  359,

      360,  361,  359,  360,  279,  358,  366,  367,  383,  366,
      367,  381,  361,  363,  364,  361,  366,  367,  380,  368,
      366,  367,  384,  366,  367,  379,  365,  330,  385,  384,
      359,  394,  378,  368,  366,  395,  368,  330,  331,  181,
      332,  359,  360,  361,  366,  367,  181,  368,  377,  376,
      332,  375,  181,  181,  361,  181,  374,  368,   59,   59,
       59,   62,   62,   62,   66,   66,   66,   72,   72,   72,
      143,  373,  143,  372,  371,  370,  362,  355,  354,  181,
      353,  181,  352,  351,  350,  349,  348,  347,  346,  181,
      345,  344,  181,  343,  342,  341,  340,  339,  338,  337,

      181,  336,  335,  334,  333,  324,  320,  317,  316,  315,
      314,  313,  312,  311,  181,  310,  309,  181,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  181,  298,
      264,  297,  296,  295,  294,  181,  293,  181,  181,  292,
      291,  290,  289,  288,  287,  284,  277,  276,  267,  266,
      265,  264,  263,  262,  181,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  181,  250,  181,  249,
      248,  181,  245,  244,  243,  242,  181,  241,  240,  239,
      236,  181,  235,  181,  181,  234,  233,  232,  231,  230,
      229,  228,  212,  207,  206,  199,  198,  197,  194,  193,

      192,  189,  188,  181,  187,  186,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      167,  166,  165,  164,  163,  162,  161,  160,  151,  150,
      142,  141,  140,  139,  138,  137,  136,  128,  121,  117,
       96,   93,   77,   76,   74,   73,  417,   11,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,

      417,  417,  417,  417,  417,  417,  417,  417
    } ;

static const flex_int16_t yy_chk[809] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,    5,    6,    5,    6,    7,    8,
        7,    8,   26,    7,    8,    5,    6,   40,   28,   43,
       26,   27,   27,   28,   32,   32,   34,   34,   43,  422,
       53,   30,   40,   30,   30,    7,    8,   29,   53,   30,

      414,    7,    8,    7,    8,   27,   30,   29,   36,   29,
       29,   30,  126,   36,   41,   29,   41,  126,   42,  413,
        7,    8,   29,   41,   44,   42,   44,   29,   42,   45,
       50,   42,   49,   70,   47,   44,   49,   45,  412,   45,
       47,   47,   45,   52,  411,   50,  130,   79,   50,  410,
       49,   85,   85,   52,   52,   70,   52,   85,   52,   79,
       79,  130,   80,   80,   70,   79,  104,  104,   80,   85,
      183,   70,   79,  183,   70,   80,   70,   79,  409,   86,
       80,   86,   86,   87,  135,   87,  408,   86,   87,   87,
       88,   88,  407,   89,   86,   89,   89,   90,   90,   86,

      134,   89,  135,   88,  120,  120,  135,  134,   89,  136,
       90,  136,  147,   89,  147,  146,  146,  147,  147,  148,
      148,  146,  149,  149,  406,  153,  153,   87,  146,  156,
      156,  153,  148,  146,  151,  149,  151,  151,  153,  152,
      172,  172,  151,  153,  208,  208,  405,  155,  155,  151,
      157,  152,  152,  154,  151,  154,  147,  152,  154,  154,
      155,  404,  157,  157,  152,  158,  158,  403,  159,  152,
      159,  159,  402,  207,  207,  157,  159,  209,  158,  207,
      210,  210,  401,  159,  218,  218,  207,  400,  159,  209,
      209,  207,  399,  210,  211,  211,  213,  154,  213,  213,

      211,  398,  209,  397,  213,  216,  216,  211,  215,  215,
      219,  213,  211,  396,  215,  222,  213,  393,  216,  217,
      217,  215,  219,  219,  220,  220,  215,  222,  222,  223,
      223,  392,  217,  224,  224,  219,  391,  220,  225,  225,
      222,  226,  223,  226,  226,  227,  224,  227,  227,  226,
      390,  225,  389,  227,  270,  388,  226,  268,  268,  387,
      227,  226,  386,  268,  382,  227,  270,  270,  271,  271,
      268,  272,  272,  273,  273,  268,  274,  274,  381,  270,
      380,  271,  274,  379,  272,  378,  273,  275,  275,  274,
      277,  277,  377,  275,  274,  376,  277,  280,  278,  278,

      275,  281,  281,  277,  278,  275,  282,  282,  277,  280,
      280,  278,  283,  283,  281,  375,  278,  284,  284,  282,
      285,  285,  280,  286,  286,  283,  317,  317,  318,  318,
      284,  319,  319,  285,  321,  321,  286,  322,  322,  317,
      321,  318,  374,  322,  319,  323,  323,  321,  324,  324,
      322,  323,  321,  325,  325,  322,  326,  326,  323,  327,
      372,  324,  330,  323,  328,  328,  325,  329,  329,  326,
      371,  327,  327,  356,  330,  330,  370,  328,  331,  331,
      329,  332,  332,  359,  327,  356,  356,  330,  357,  357,
      355,  331,  358,  358,  332,  359,  359,  363,  356,  360,

      360,  357,  361,  361,  366,  358,  364,  364,  359,  363,
      363,  354,  360,  365,  365,  361,  366,  366,  353,  364,
      367,  367,  363,  368,  368,  352,  365,  369,  369,  366,
      383,  383,  348,  367,  384,  384,  368,  385,  385,  347,
      369,  394,  394,  383,  395,  395,  346,  384,  345,  344,
      385,  343,  342,  341,  394,  339,  338,  395,  418,  418,
      418,  419,  419,  419,  420,  420,  420,  421,  421,  421,
      423,  337,  423,  336,  335,  333,  320,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  292,

      291,  290,  289,  288,  287,  279,  276,  269,  267,  266,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  221,  214,  212,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  182,  180,  179,  178,  177,  176,  175,  174,  173,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  150,  145,  137,  133,  132,  131,  129,  128,

      127,  125,  124,  123,  122,  121,  119,  117,  116,  115,
      114,  113,  112,  111,  110,  109,  108,  107,  106,  105,
      103,  102,  101,  100,   99,   98,   97,   96,   84,   81,
       68,   65,   64,   61,   57,   55,   54,   51,   48,   46,
       35,   33,   24,   20,   16,   15,   11,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,

      417,  417,  417,  417,  417,  417,  417,  417
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[66] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 
    0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
    /* 
        António Lopes - 2017262466;
        Tiago Fernandes - 2017242428;
    */  
    #include <string.h>
    #include "y.tab.h"
    #define LOCATION yylloc.first_line = yylloc.last_line = yylineno, yylloc.first_column = num_colunas - yyleng, yylloc.last_column = num_colunas + strlen(yytext) - 1, yycolumn += yyleng;
   
    int imprime, erros, return_flag; // Definidas no jucompiler.y
    int num_linhas = 1;
    int num_colunas = 1;
    int yycolumn = 1;
    int parse_error = 0;
    extern int error_tag;
    int errorline = 1, errorcol = 1;    // Erros nas STRLIT e BLOCKCOMMENT
    int commentline, commentcol;
    char string[1024] = "";
    void printString(char * string);
    int erro = 0;
#line 806 "lex.yy.c"
/* Contador de linhas do lex */

#line 809 "lex.yy.c"

#define INITIAL 0
#define LINECOMMENT 1
#define BLOCKCOMMENT 2
#define STRINGLIT 3
#define TERMINATOR 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 50 "jucompiler.l"


#line 1033 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 418 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 748 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{
                            if(imprime==1){
                                printf("INTLIT(%s)\n", yytext);
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            yylval.str = (char *) strdup(yytext);
                            if(return_flag == 1){
                                return INTLIT;
                            }
                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "jucompiler.l"
{
                            if(imprime==1){
                                printf("REALLIT(%s)\n", yytext);
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            yylval.str = (char *) strdup(yytext);
                            if(return_flag == 1){
                                return REALLIT;
                            }
                        }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 76 "jucompiler.l"
{
                            num_linhas++;
                            num_colunas = 1;
                            yycolumn = 1;
                            LOCATION;
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{
                            if(imprime==1){
                                printf("BOOLLIT(%s)\n", yytext);
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            yylval.str = (char *) strdup(yytext);
                            if(return_flag == 1){
                                return BOOLLIT;
                            }
                        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{
                            if(imprime==1){
                                printf("AND\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return AND;
                            }
                        }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{
                            if(imprime==1){
                                printf("ASSIGN\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return ASSIGN;
                            }
                        }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{
                            if(imprime==1){
                                printf("STAR\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return STAR;
                            }
                        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 128 "jucompiler.l"
{
                            if(imprime==1){
                                printf("COMMA\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return COMMA;
                            }
                        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 139 "jucompiler.l"
{
                            if(imprime==1){
                                printf("DIV\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return DIV;
                            }
                        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 150 "jucompiler.l"
{
                            if(imprime==1){
                                printf("EQ\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return EQ;
                            }
                        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 161 "jucompiler.l"
{
                            if(imprime==1){
                                printf("GE\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return GE;
                            }
                        }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 172 "jucompiler.l"
{
                            if(imprime==1){
                                printf("GT\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return GT;
                            }
                        }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 183 "jucompiler.l"
{
                            if(imprime==1){
                                printf("IF\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return IF;
                            }
                        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 194 "jucompiler.l"
{
                            if(imprime==1){
                                printf("LBRACE\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return LBRACE;
                            }
                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 205 "jucompiler.l"
{
                            if(imprime==1){
                                printf("LE\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return LE;
                            }
                        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 216 "jucompiler.l"
{
                            if(imprime==1){
                                printf("LPAR\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return LPAR;
                            }
                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 227 "jucompiler.l"
{
                            if(imprime==1){
                                printf("LSQ\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return LSQ;
                            }
                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 238 "jucompiler.l"
{
                            if(imprime==1){
                                printf("LT\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return LT;
                            }
                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 249 "jucompiler.l"
{
                            if(imprime==1){
                                printf("MINUS\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return MINUS;
                            }
                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 260 "jucompiler.l"
{
                            if(imprime==1){
                                printf("MOD\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return MOD;
                            }
                        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 271 "jucompiler.l"
{
                            if(imprime==1){
                                printf("NE\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return NE;
                            }
                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 282 "jucompiler.l"
{
                            if(imprime==1){
                                printf("NOT\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return NOT;
                            }
                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 293 "jucompiler.l"
{
                            if(imprime==1){
                                printf("OR\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return OR;
                            }
                        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 304 "jucompiler.l"
{
                            if(imprime==1){
                                printf("PLUS\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return PLUS;
                            }
                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 315 "jucompiler.l"
{
                            if(imprime==1){
                                printf("RBRACE\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return RBRACE;
                            }
                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 326 "jucompiler.l"
{
                            if(imprime==1){
                                printf("RPAR\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return RPAR;
                            }
                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 337 "jucompiler.l"
{
                            if(imprime==1){
                                printf("RSQ\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return RSQ;
                            }
                        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 348 "jucompiler.l"
{
                            if(imprime==1){
                                printf("SEMICOLON\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return SEMICOLON;
                            }
                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 359 "jucompiler.l"
{
                            if(imprime==1){
                                printf("ARROW\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return ARROW;
                            }
                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 370 "jucompiler.l"
{
                            if(imprime==1){
                                printf("LSHIFT\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return LSHIFT;
                            }
                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 381 "jucompiler.l"
{
                            if(imprime==1){
                                printf("RSHIFT\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return RSHIFT;
                            }
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 392 "jucompiler.l"
{
                            if(imprime==1){
                                printf("XOR\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return XOR;
                            }
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 403 "jucompiler.l"
{
                            if(imprime==1){
                                printf("BOOL\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return BOOL;
                            }
                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 414 "jucompiler.l"
{
                            if(imprime==1){
                                printf("CLASS\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return CLASS;
                            }
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 425 "jucompiler.l"
{
                            if(imprime==1){
                                printf("DOTLENGTH\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return DOTLENGTH;
                            }
                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 436 "jucompiler.l"
{
                            if(imprime==1){
                                printf("DOUBLE\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return DOUBLE;
                            }
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 447 "jucompiler.l"
{
                            if(imprime==1){
                                printf("ELSE\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return ELSE;
                            }
                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 458 "jucompiler.l"
{
                            if(imprime==1){
                                printf("INT\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return INT;
                            }
                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 470 "jucompiler.l"
{
                            if(imprime==1){
                                printf("PRINT\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return PRINT;
                            }
                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 481 "jucompiler.l"
{
                            if(imprime==1){
                                printf("PARSEINT\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return PARSEINT;
                            }
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 492 "jucompiler.l"
{
                            if(imprime==1){
                                printf("PUBLIC\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){ 
                                return PUBLIC;
                            }
                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 503 "jucompiler.l"
{
                            if(imprime==1){
                                printf("RETURN\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){ 
                                return RETURN;
                            }
                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 514 "jucompiler.l"
{
                            if(imprime==1){
                                printf("STATIC\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){ 
                                return STATIC;
                            }
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 525 "jucompiler.l"
{
                            if(imprime==1){
                                printf("STRING\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){ 
                                return STRING;
                            }
                        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 536 "jucompiler.l"
{
                            if(imprime==1){
                                printf("VOID\n");
                            }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){ 
                                return VOID;
                            }
                        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 547 "jucompiler.l"
{
                            if(imprime==1){
                                printf("WHILE\n");
                                }
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){
                                return WHILE;
                            }
                        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 558 "jucompiler.l"
{
                            num_colunas += yyleng;
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 562 "jucompiler.l"
{
                            if(imprime==1){
                                printf("RESERVED(%s)\n", yytext);
                            } 
                            yylval.str = (char *) strdup(yytext);
                            num_colunas += yyleng;
                            LOCATION;
                            if(return_flag == 1){ 
                                return RESERVED;
                            }
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 574 "jucompiler.l"
{
                            if(imprime==1){
                                printf("ID(%s)\n", yytext);
                            } 
                            num_colunas += yyleng;
                            LOCATION;
                            yylval.str = (char *) strdup(yytext);
                            if(return_flag == 1){ 
                                return ID;
                            }
                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 587 "jucompiler.l"
{
                                BEGIN LINECOMMENT;
                            }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 591 "jucompiler.l"
{
                                num_linhas++;
                                num_colunas = 1;
                                BEGIN 0;
                            }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 597 "jucompiler.l"
{;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 600 "jucompiler.l"
{
                            parse_error = 0; 
                            LOCATION;
                            BEGIN BLOCKCOMMENT; 
                            commentline = num_linhas; 
                            commentcol = num_colunas; 
                            num_colunas += yyleng;
                        }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 609 "jucompiler.l"
{
                            parse_error = 0; 
                            num_linhas++; 
                            num_colunas = 1;
                        }
	YY_BREAK
case YY_STATE_EOF(BLOCKCOMMENT):
#line 615 "jucompiler.l"
{
                            parse_error = 0; 
                            if(imprime == 1 || erros == 1){
                                parse_error = 1; 
                                printf("Line %d, col %d: unterminated comment\n", commentline, commentcol); 
                                errorline = num_linhas; errorcol = num_colunas;
                            } 
                            return 0;
                        }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 625 "jucompiler.l"
{
                            parse_error = 0; 
                            num_colunas += yyleng;
                        }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 630 "jucompiler.l"
{
                            parse_error = 0; 
                            BEGIN 0; 
                            num_colunas += yyleng;
                        }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 637 "jucompiler.l"
{
                                BEGIN STRINGLIT; 
                                strcpy(string,"\""); 
                                erro = 0; 
                                errorcol = num_colunas; 
                                errorline=num_linhas; 
                                num_colunas += yyleng;
                            }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 646 "jucompiler.l"
{
                                strcat(string, "\""); 
                                if(erro == 0){
                                    printString(string); 
                                    BEGIN 0; 
                                    num_colunas += yyleng;
                                    yytext = string;
                                    yylval.str = (char *) strdup(string); 
                                    if(return_flag == 1){
                                        return STRLIT;
                                    }
                                }
                                else{
                                    BEGIN 0; 
                                    num_colunas += yyleng;
                                }
                            }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 664 "jucompiler.l"
{
                                if (imprime == 1 || erros == 1){
                                    printf("Line %d, col %d: unterminated string literal\n", errorline, errorcol);
                                }
                                num_linhas++; 
                                num_colunas = 1; 
                                BEGIN 0;
                            }
	YY_BREAK
case YY_STATE_EOF(STRINGLIT):
#line 673 "jucompiler.l"
{
                                if (imprime == 1 || erros == 1){
                                    printf("Line %d, col %d: unterminated string literal\n", errorline, errorcol);
                                } 
                                BEGIN 0;
                                return 0;
                            }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 681 "jucompiler.l"
{
                                if (imprime == 1 || erros == 1){
                                    printf("Line %d, col %d: invalid escape sequence (%s)\n", errorline, num_colunas, yytext);
                                } 
                                num_colunas += yyleng; 
                                erro = 1;
                            }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 689 "jucompiler.l"
{
                                strcat(string, yytext); 
                                num_colunas += yyleng;
                            }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 694 "jucompiler.l"
{
                                strcat(string, yytext); 
                                num_colunas += yyleng;
                            }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 699 "jucompiler.l"
{
                                strcat(string, yytext); 
                                num_colunas += yyleng;
                            }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LINECOMMENT):
case YY_STATE_EOF(TERMINATOR):
#line 704 "jucompiler.l"
{
                    parse_error = 1;
                    return 0;
                }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 709 "jucompiler.l"
{
                    if(imprime == 1 || erros == 1){
                        printf("Line %d, col %d: illegal character (%s)\n", num_linhas, num_colunas, yytext);
                    } 
                    num_colunas += yyleng;
                }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 716 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1970 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 418 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 418 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 417);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 716 "jucompiler.l"


void printString(char * string){
    if (erro == 0){
        if(imprime == 1){
            printf("STRLIT(%s)\n", string);
        }
    }
}

void yyerror(char *s){
    error_tag = 1;
    if (parse_error){
        printf("Line %d, col %d: %s: %s\n", num_linhas, num_colunas, s, yytext);
    }
    else{
        printf("Line %d, col %d: %s: %s\n", num_linhas, (int)(num_colunas - strlen(yytext)), s, yytext);
    }
}

int yywrap(){
    return 1;
}

