
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[446] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       66,   64,   47,    3,    3,   22,   57,   49,   20,   64,
       16,   26,    7,   24,    8,   19,   64,    9,    1,    1,
       28,   18,    6,   12,   49,   49,   17,   27,   32,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   14,   64,
       25,   52,   51,   51,   55,   54,   54,   55,   62,   59,
       59,   58,   60,   63,   65,    3,   21,   49,    5,   48,
       29,    2,    2,    0,   53,   50,    0,    2,    0,    0,
        0,    1,    0,   30,   15,   10,   11,   31,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   48,   49,   49,   49,   49,   49,   49,   49,   49,
       13,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   23,   51,   54,   56,   59,   60,   61,
        0,    2,    0,    0,    0,    0,    0,    2,    2,    0,
        0,    0,    2,    2,    0,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   48,   49,   49,
       49,   38,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,    2,    0,    2,
        2,    2,    0,    0,    0,    2,    0,    0,    0,    2,
        2,    0,    2,    2,    0,    0,    0,    0,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   37,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   48,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,    4,
       45,   49,   49,    2,    0,    2,    2,    0,    0,    2,
        2,    0,    2,    2,    0,    2,    2,    0,    0,    2,

        2,    2,   49,   49,   49,   49,   49,   49,   34,   49,
       49,   49,   49,   49,   48,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   48,   49,   49,   46,    2,    2,    2,    0,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,   49,   44,   48,   49,   49,   49,   49,   36,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       41,   49,   42,   43,   49,   49,   49,   49,    2,    2,
        2,    2,    2,    2,   35,    2,    2,    2,    2,    2,
        2,    2,   48,    0,   49,   33,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,    2,    2,
        2,    0,    0,   49,   49,   49,   49,   49,   49,   49,
        2,    2,    0,    0,   49,   49,   49,   49,    0,    0,
       49,    0,    0,   49,    0,    0,    0,    0,    0,    0,
        0,    0,   40,   39,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,    9,    9,    9,    9,   26,    9,
        9,    9,   27,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   28,    9,    9,    9,    9,    9,    9,    9,
       29,   30,   31,   32,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,    9,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[452] =
    {   0,
        0,    0,   59,   60,   63,   64,   67,   68,    0,    0,
      780,  781,  781,  781,  776,  754,  781,    0,  781,  766,
      781,  781,  781,  761,  781,   57,   63,   66,   92,   96,
      781,   63,  751,   64,  728,   38,  781,  781,  781,   57,
       44,   92,   55,   65,   93,  726,   99,  725,  724,   94,
      722,  107,  731,  101,  102,  717,  720,  725,  781,  705,
      781,  781,  781,  761,  781,  781,  760,  743,  781,  781,
      758,  781,  138,  781,  781,  781,  781,    0,  781,  781,
      781,  141,  143,  722,  781,  781,  738,  145,  171,  165,
      173,  181,  175,  781,  781,  781,  781,  781,  706,  707,

      705,  704,  703,  706,  714,  699,   68,  716,  715,  702,
      708,  693,  694,  691,  103,  699,  696,  694,  690,  687,
        0,  690,  121,  691,  699,  683,  679,  689,  694,  695,
      128,  695,   47,  682,   81,  680,  685,  680,  161,  164,
      687,   37,  682,  781,  781,  781,  781,  781,  781,  781,
      702,  202,  195,  206,  209,  676,  223,  212,  226,  245,
      237,  216,  255,  247,  251,  683,  678,  667,  666,  679,
      672,  681,  676,  675,  676,  661,  659,  202,  675,  673,
      669,  661,  658,  666,  652,  668,  667,    0,  653,  187,
      647,  660,  657,  643,  653,  650,  647,  649,  637,   96,

      646,  636,  635,  637,  634,  643,  646,  631,  646,  630,
      633,  633,  640,  626,  639,  641,  630,  253,  261,  275,
      273,  277,  633,  281,  651,  291,  300,  302,  305,  310,
      307,  650,  324,  316,  318,  321,  332,  341,  630,  623,
      630,  617,  616,  627,  621,  622,  611,  609,  618,  606,
      614,    0,  607,  610,  617,  610,  601,  614,  601,  616,
      599,  604,  593,  595,  611,  610,  605,  600,  599,  598,
      589,  586,  595,  600,  585,  598,  592,  577,  580,    0,
        0,  578,  591,  343,  607,  352,  335,  357,  362,  366,
      368,  575,  376,  387,  605,  390,  395,  397,  401,  406,

      411,  415,  587,  584,  578,  588,  569,  586,    0,  573,
      574,  579,  564,  578,  570,  568,  560,  565,  571,  571,
      570,  567,  554,  569,  567,  567,  552,  555,  563,  532,
      542,  532,  530,  538,  536,    0,  417,  420,  422,  536,
      425,  436,  439,  446,  450,  455,  460,  464,  466,  470,
      474,  480,  526,    0,  556,  534,  522,  511,  508,    0,
      503,  499,  489,  506,  504,  502,  492,  484,  468,  474,
        0,  468,    0,    0,  459,  449,  240,  445,  484,  488,
      490,  494,  498,  504,  781,  508,  512,  514,  518,  522,
      528,  532,  464,  426,  412,    0,  423,  408,  414,  413,

      409,  382,  378,  376,  373,  366,  363,  365,  536,  538,
      542,  352,  340,  339,  337,  342,  338,  329,  314,  294,
      546,  552,  313,  294,  283,  277,  255,  271,  254,  282,
      252,  236,  237,  214,  210,  174,  191,  171,  159,  154,
      135,  126,  781,  781,  781,  585,  588,  591,  594,  156,
      597
    } ;

static const flex_int16_t yy_def[452] =
    {   0,
      445,    1,  446,  446,  447,  447,  448,  448,  449,  449,
      445,  445,  445,  445,  445,  445,  445,  450,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  450,  450,  445,  445,  445,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  451,  445,  445,  445,  445,  450,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  450,  450,

      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,

      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  450,  445,  450,  450,  450,  450,  450,  450,

      450,  450,  450,  450,  450,  450,  450,  450,  445,  445,
      445,  445,  445,  450,  450,  450,  450,  450,  450,  450,
      445,  445,  445,  445,  450,  450,  450,  450,  445,  445,
      450,  445,  445,  450,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,    0,  445,  445,  445,  445,  445,
      445
    } ;

static const flex_int16_t yy_nxt[843] =
    {   0,
       12,   13,   14,   13,   15,   13,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   18,   35,   36,   37,   12,
       38,   39,   18,   40,   41,   42,   43,   44,   45,   46,
       18,   47,   18,   48,   49,   50,   51,   52,   18,   53,
       54,   55,   56,   57,   58,   18,   18,   18,   59,   60,
       61,   63,   63,   64,   64,   66,   66,   67,   67,   70,
       70,   71,   71,   80,   72,   72,   68,   68,  215,   85,
      216,   81,   82,   83,   86,   94,   95,   97,   98,  100,
      104,  102,  111,  105,  101,  202,   73,   73,  203,   87,

      106,  112,   74,   74,   74,   74,   84,  103,  113,   88,
      114,   89,   89,   88,  205,   92,   92,   90,  174,  175,
      115,   90,   74,   74,   91,  107,  116,  126,   93,   90,
      206,  127,  108,   90,  117,  109,  118,  121,  110,  119,
      130,  134,  139,  122,  123,  150,  128,  267,  151,  268,
      183,  140,  135,  136,  184,  137,  131,  138,   78,  132,
      152,  152,  152,  152,  158,  159,  153,  150,  153,  199,
      160,  191,  192,  154,  200,  155,  150,  444,  153,  162,
      153,  162,  160,  150,  163,  164,  443,  150,   88,  150,
       89,   89,   89,  165,   92,   92,   90,  212,   88,  442,

       92,   92,  210,  161,  441,  161,   90,   93,   90,  219,
      211,  219,  440,   93,  220,  221,  213,  439,   90,  225,
      188,  152,  152,  438,  162,  152,  222,  153,  152,  152,
      258,  226,  226,  259,  155,  163,  164,  160,  155,  153,
       88,  155,  224,  224,  227,  226,  226,  437,   90,  160,
      188,  160,  248,  249,  219,  224,   89,   89,  228,  229,
       90,  229,  232,  160,  230,  231,  233,  234,   88,  161,
      237,  237,  284,  284,  233,  234,   90,  406,  153,  236,
      220,  221,  285,  238,  436,  284,  435,  235,   90,  434,
      153,  407,  286,  287,  286,  287,  290,  290,   88,  433,

      224,  224,  153,  432,  229,  289,   90,  288,  188,  291,
      226,  226,  431,  224,  153,  188,  160,  295,   90,  226,
      294,  226,  226,  228,  230,  231,  296,  297,  160,  296,
      297,  232,  228,  188,  228,  233,  234,  301,  302,  299,
      301,  301,  298,  233,  234,  430,  429,  428,  236,   88,
      236,  237,  237,  236,  286,  287,  235,   90,   88,  285,
      237,  237,  284,  284,  238,  188,   90,  289,  153,   90,
      427,  286,  287,  238,  188,  284,  338,  339,   90,  188,
      153,  338,  338,  426,  288,  290,  290,  290,  290,  289,
      425,  153,  424,  153,  289,  341,  341,  295,  291,  423,

      291,  160,  188,  153,  420,  153,  342,  342,  341,  296,
      297,  419,  160,  160,  296,  297,  345,  346,  418,  343,
      345,  345,  298,  188,  160,  347,  348,  299,  188,  299,
      233,  234,  188,  299,  350,  351,  379,  380,  349,  286,
      287,  382,  383,  236,  341,  341,  417,  352,  416,  381,
      160,  415,  289,  414,  384,  342,  342,  341,  342,  342,
      188,  160,  160,  188,  160,  386,  387,  232,  343,  296,
      297,  343,  413,  160,  389,  390,  160,  232,  388,  350,
      351,  412,  299,  350,  351,  347,  348,  391,  408,  350,
      351,  285,  392,  350,  351,  405,  352,  404,  349,  350,

      351,  285,  392,  382,  383,  403,  352,  382,  383,  379,
      380,  402,  352,  382,  383,  295,  409,  382,  383,  401,
      384,  188,  381,  382,  383,  295,  409,  389,  390,  188,
      384,  389,  390,  386,  387,  400,  384,  389,  390,  399,
      410,  389,  390,  398,  391,  188,  388,  389,  390,  188,
      410,  350,  411,  188,  391,  382,  421,  389,  422,  188,
      391,  350,  351,  397,  352,  382,  383,  396,  384,  395,
      391,  389,  390,  394,  352,  393,  385,  378,  384,  377,
      188,  376,  188,  375,  391,   62,   62,   62,   65,   65,
       65,   69,   69,   69,   75,   75,   75,  149,  374,  149,

      373,  372,  371,  370,  369,  368,  367,  188,  188,  366,
      365,  188,  364,  363,  362,  361,  360,  359,  358,  357,
      188,  356,  355,  354,  353,  344,  340,  337,  336,  335,
      334,  333,  332,  331,  188,  330,  329,  188,  328,  327,
      326,  325,  324,  323,  322,  188,  321,  320,  319,  318,
      317,  316,  188,  315,  280,  314,  313,  312,  311,  310,
      188,  309,  188,  188,  308,  307,  306,  305,  304,  303,
      300,  293,  292,  283,  282,  281,  188,  280,  279,  278,
      188,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      266,  265,  264,  188,  263,  262,  188,  261,  260,  188,

      257,  256,  255,  254,  253,  188,  252,  251,  250,  247,
      188,  246,  188,  188,  245,  244,  243,  242,  241,  240,
      239,  223,  218,  217,  214,  209,  208,  207,  204,  201,
      198,  197,  196,  188,  195,  194,  193,  190,  189,  188,
      187,  186,  185,  182,  181,  180,  179,  178,  177,  176,
      173,  172,  171,  170,  169,  168,  167,  166,  157,  156,
      148,  147,  146,  145,  144,  143,  142,  141,  133,  129,
      125,  124,  120,   99,   96,   80,   79,   77,   76,  445,
       11,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445
    } ;

static const flex_int16_t yy_chk[843] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    3,    4,    5,    6,    5,    6,    7,
        8,    7,    8,   26,    7,    8,    5,    6,  142,   28,
      142,   26,   27,   27,   28,   32,   32,   34,   34,   36,
       41,   40,   43,   41,   36,  133,    7,    8,  133,   29,

       41,   43,    7,    8,    7,    8,   27,   40,   44,   29,
       44,   29,   29,   30,  135,   30,   30,   29,  107,  107,
       44,   30,    7,    8,   29,   42,   45,   50,   30,   29,
      135,   50,   42,   30,   45,   42,   45,   47,   42,   45,
       52,   54,   55,   47,   47,   73,   50,  200,   82,  200,
      115,   55,   54,   54,  115,   54,   52,   54,  450,   52,
       82,   82,   83,   83,   88,   88,   82,   73,   83,  131,
       88,  123,  123,   82,  131,   83,   73,  442,   82,   90,
       83,   90,   88,   73,   90,   90,  441,   73,   89,   73,
       89,   89,   91,   91,   93,   93,   89,  140,   92,  440,

       92,   92,  139,   89,  439,   91,   92,   93,   89,  153,
      139,  153,  438,   92,  153,  153,  140,  437,   92,  158,
      140,  152,  152,  436,   90,  154,  154,  152,  155,  155,
      190,  158,  158,  190,  152,  162,  162,  158,  154,  152,
      157,  155,  157,  157,  158,  159,  159,  435,  157,  158,
      434,  159,  178,  178,  153,  157,  161,  161,  159,  160,
      157,  160,  163,  159,  160,  160,  164,  164,  165,  161,
      165,  165,  218,  218,  163,  163,  165,  377,  218,  164,
      219,  219,  220,  165,  433,  218,  432,  163,  165,  431,
      218,  377,  221,  221,  220,  220,  222,  222,  224,  430,

      224,  224,  222,  429,  160,  221,  224,  220,  428,  222,
      226,  226,  427,  224,  222,  426,  226,  230,  224,  227,
      227,  228,  228,  226,  229,  229,  231,  231,  226,  230,
      230,  233,  227,  425,  228,  234,  234,  235,  235,  231,
      236,  236,  230,  233,  233,  424,  423,  420,  234,  237,
      235,  237,  237,  236,  287,  287,  233,  237,  238,  286,
      238,  238,  284,  284,  237,  419,  238,  287,  284,  237,
      418,  286,  286,  238,  417,  284,  288,  288,  238,  416,
      284,  289,  289,  415,  286,  290,  290,  291,  291,  288,
      414,  290,  413,  291,  289,  293,  293,  296,  290,  412,

      291,  293,  408,  290,  407,  291,  294,  294,  293,  296,
      296,  406,  294,  293,  297,  297,  298,  298,  405,  294,
      299,  299,  296,  404,  294,  300,  300,  297,  403,  298,
      301,  301,  402,  299,  302,  302,  337,  337,  300,  338,
      338,  339,  339,  301,  341,  341,  401,  302,  400,  337,
      341,  399,  338,  398,  339,  342,  342,  341,  343,  343,
      397,  342,  341,  395,  343,  344,  344,  347,  342,  345,
      345,  343,  394,  342,  346,  346,  343,  350,  344,  347,
      347,  393,  345,  348,  348,  349,  349,  346,  378,  350,
      350,  379,  347,  351,  351,  376,  348,  375,  349,  352,

      352,  382,  350,  379,  379,  372,  351,  380,  380,  381,
      381,  370,  352,  382,  382,  386,  379,  383,  383,  369,
      380,  368,  381,  384,  384,  389,  382,  386,  386,  367,
      383,  387,  387,  388,  388,  366,  384,  389,  389,  365,
      386,  390,  390,  364,  387,  363,  388,  391,  391,  362,
      389,  392,  392,  361,  390,  409,  409,  410,  410,  359,
      391,  411,  411,  358,  392,  421,  421,  357,  409,  356,
      410,  422,  422,  355,  411,  353,  340,  335,  421,  334,
      333,  332,  331,  330,  422,  446,  446,  446,  447,  447,
      447,  448,  448,  448,  449,  449,  449,  451,  329,  451,

      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  308,
      307,  306,  305,  304,  303,  295,  292,  285,  283,  282,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      232,  225,  223,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  189,

      187,  186,  185,  184,  183,  182,  181,  180,  179,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  156,  151,  143,  141,  138,  137,  136,  134,  132,
      130,  129,  128,  127,  126,  125,  124,  122,  120,  119,
      118,  117,  116,  114,  113,  112,  111,  110,  109,  108,
      106,  105,  104,  103,  102,  101,  100,   99,   87,   84,
       71,   68,   67,   64,   60,   58,   57,   56,   53,   51,
       49,   48,   46,   35,   33,   24,   20,   16,   15,   11,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[66] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 
    0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
    /* 
        António Lopes - 2017262466;
        Tiago Fernandes - 2017242428;
    */  
    #include <string.h>
    int imprime = 0;
    int erros = 0;
    int num_linhas = 1;
    int num_colunas = 1;
    int errorline, errorcol;
    int commentline, commentcol;
    char string[1024] = "";
    void printString(char * string);
    int erro = 0;
#line 819 "lex.yy.c"
/* Contador de linhas do lex */

#line 822 "lex.yy.c"

#define INITIAL 0
#define LINECOMMENT 1
#define BLOCKCOMMENT 2
#define STRINGLIT 3
#define TERMINATOR 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 45 "jucompiler.l"


#line 1046 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 446 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 781 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{if(imprime==1){printf("INTLIT(%s)\n", yytext);} num_colunas += yyleng;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{if(imprime==1){printf("REALLIT(%s)\n", yytext);} num_colunas += yyleng;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 49 "jucompiler.l"
{num_linhas++;num_colunas = 1;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 50 "jucompiler.l"
{if(imprime==1){printf("BOOLLIT(%s)\n", yytext);} num_colunas += yyleng;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{if(imprime==1){printf("AND\n");} num_colunas += yyleng;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{if(imprime==1){printf("ASSIGN\n");}num_colunas += yyleng;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{if(imprime==1){printf("STAR\n");}num_colunas += yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{if(imprime==1){printf("COMMA\n");}num_colunas += yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{if(imprime==1){printf("DIV\n");}num_colunas += yyleng;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "jucompiler.l"
{if(imprime==1){printf("EQ\n");}num_colunas += yyleng;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{if(imprime==1){printf("GE\n");}num_colunas += yyleng;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "jucompiler.l"
{if(imprime==1){printf("GT\n");}num_colunas += yyleng;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 59 "jucompiler.l"
{if(imprime==1){printf("IF\n");}num_colunas += yyleng;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 60 "jucompiler.l"
{if(imprime==1){printf("LBRACE\n");}num_colunas += yyleng;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{if(imprime==1){printf("LE\n");}num_colunas += yyleng;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 62 "jucompiler.l"
{if(imprime==1){printf("LPAR\n");}num_colunas += yyleng;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 63 "jucompiler.l"
{if(imprime==1){printf("LSQ\n");}num_colunas += yyleng;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 64 "jucompiler.l"
{if(imprime==1){printf("LT\n");}num_colunas += yyleng;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{if(imprime==1){printf("MINUS\n");}num_colunas += yyleng;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{if(imprime==1){printf("MOD\n");}num_colunas += yyleng;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{if(imprime==1){printf("NE\n");}num_colunas += yyleng;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{if(imprime==1){printf("NOT\n");}num_colunas += yyleng;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{if(imprime==1){printf("OR\n");}num_colunas += yyleng;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 70 "jucompiler.l"
{if(imprime==1){printf("PLUS\n");}num_colunas += yyleng;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{if(imprime==1){printf("RBRACE\n");}num_colunas += yyleng;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{if(imprime==1){printf("RPAR\n");}num_colunas += yyleng;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{if(imprime==1){printf("RSQ\n");}num_colunas += yyleng;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 74 "jucompiler.l"
{if(imprime==1){printf("SEMICOLON\n");}num_colunas += yyleng;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{if(imprime==1){printf("ARROW\n");}num_colunas += yyleng;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{if(imprime==1){printf("LSHIFT\n");}num_colunas += yyleng;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{if(imprime==1){printf("RSHIFT\n");}num_colunas += yyleng;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{if(imprime==1){printf("XOR\n");}num_colunas += yyleng;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{if(imprime==1){printf("BOOL\n");}num_colunas += yyleng;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{if(imprime==1){printf("CLASS\n");}num_colunas += yyleng;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{if(imprime==1){printf("DOTLENGTH\n");}num_colunas += yyleng;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{if(imprime==1){printf("DOUBLE\n");}num_colunas += yyleng;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{if(imprime==1){printf("ELSE\n");}num_colunas += yyleng;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{if(imprime==1){printf("INT\n");}num_colunas += yyleng;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{if(imprime==1){printf("PRINT\n");}num_colunas += yyleng;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{if(imprime==1){printf("PARSEINT\n");}num_colunas += yyleng;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{if(imprime==1){printf("PUBLIC\n");}num_colunas += yyleng;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{if(imprime==1){printf("RETURN\n");}num_colunas += yyleng;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{if(imprime==1){printf("STATIC\n");}num_colunas += yyleng;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{if(imprime==1){printf("STRING\n");}num_colunas += yyleng;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{if(imprime==1){printf("VOID\n");}num_colunas += yyleng;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{if(imprime==1){printf("WHILE\n");}num_colunas += yyleng;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{num_colunas += yyleng;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 94 "jucompiler.l"
{if(imprime==1){printf("RESERVED(%s)\n", yytext);} num_colunas += yyleng;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{if(imprime==1){printf("ID(%s)\n", yytext);} num_colunas += yyleng;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{BEGIN LINECOMMENT;}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 99 "jucompiler.l"
{num_linhas++; num_colunas = 1; BEGIN 0;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 100 "jucompiler.l"
{;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 102 "jucompiler.l"
{BEGIN BLOCKCOMMENT; commentline = num_linhas; commentcol = num_colunas; num_colunas += yyleng;}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 103 "jucompiler.l"
{num_linhas++; num_colunas = 1;}
	YY_BREAK
case YY_STATE_EOF(BLOCKCOMMENT):
#line 104 "jucompiler.l"
{if(imprime == 1 || erros == 1){printf("Line %d, col %d: unterminated comment\n", commentline, commentcol);} return 0;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{num_colunas += yyleng;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{BEGIN 0; num_colunas += yyleng;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 108 "jucompiler.l"
{BEGIN STRINGLIT; strcpy(string,"\""); erro = 0; errorcol = num_colunas; errorline=num_linhas; num_colunas += yyleng;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{strcat(string, "\""); if(erro == 0){printString(string);BEGIN 0; num_colunas += yyleng;} else {BEGIN 0; num_colunas += yyleng;}}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 110 "jucompiler.l"
{if (imprime == 1 || erros == 1){printf("Line %d, col %d: unterminated string literal\n", errorline, errorcol);} num_linhas++; num_colunas = 1; BEGIN 0;}
	YY_BREAK
case YY_STATE_EOF(STRINGLIT):
#line 111 "jucompiler.l"
{if (imprime == 1 || erros == 1){printf("Line %d, col %d: unterminated string literal\n", errorline, errorcol);} BEGIN 0;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 112 "jucompiler.l"
{if (imprime == 1 || erros == 1){printf("Line %d, col %d: invalid escape sequence (%s)\n", errorline, num_colunas, yytext);} num_colunas += yyleng; erro = 1;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{strcat(string, yytext); num_colunas += yyleng;}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 114 "jucompiler.l"
{strcat(string, yytext); num_colunas += yyleng;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{strcat(string, yytext); num_colunas += yyleng;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LINECOMMENT):
case YY_STATE_EOF(TERMINATOR):
#line 117 "jucompiler.l"
{num_colunas += 1; return 0;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{if(imprime == 1 || erros == 1){printf("Line %d, col %d: illegal character (%s)\n", num_linhas, num_colunas, yytext);} num_colunas += yyleng;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 120 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1457 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 446 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 446 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 445);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 120 "jucompiler.l"


void printString(char * string){
    if (erro == 0){
        if(imprime == 1){
            printf("STRLIT(%s)\n", string);
        }
    }
}

int main(int argc, char *argv[]){
    if (argc > 1){
        if (strcmp(argv[1], "-l") == 0){
            imprime = 1;
            erros = 1;
        }
        else if (strcmp(argv[1], "-e1") == 0){
            erros = 1;
        }
        else{
            return 0;
        }
    }
    if (argc == 1){
        erros = 1;
    }
    yylex();
    return 0;
}

int yywrap(){
    return 1;
}
